modLoader="javafml" #mandatory
loaderVersion="[2,)" #mandatory
issueTrackerURL="https://github.com/FinnSetchell/MoogsSoaringStructures/issues" #optional
license="GNU Lesser General Public License v3.0"

[[mods]] #mandatory
    modId="mss" #mandatory
    logoFile= "assets/mss/icon.png"
    logoBlur=false
    version="${version}" #mandatory
    displayName="Moog's Soaring Structures" #mandatory
    displayURL="https://www.curseforge.com/minecraft/mc-mods/moogs-soaring-structures"
    authors="FinnDog"
    credits="Thanks to all of the builders and contributors as well as TelepathicGrunt for their structure mod template and rs!"
    description = '''lots of structures made with vanilla blocks and entities bringing life to your world!
    Discover loot, enemies, & villagers along the way!

    Join our community here: https://discord.gg/S5nffJbuvA
    ''' #mandatory (Supports multiline text)

[[mixins]]
    config = "mss-neoforge.mixins.json"

[[mixins]]
    config = "mss-common.mixins.json"

[[dependencies.mss]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,)"